package com.mine.vo;

import lombok.Data;

import java.io.Serializable;

/**
 * @author 杜晓鹏
 * @create 2019-01-11 17:11
 */
@Data
public class ShippingVO implements Serializable {
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shopping.receiver_phone
     *
     * @mbg.generated
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shopping.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shopping.receiver_province
     *
     * @mbg.generated
     */
    private String receiverProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shopping.receiver_city
     *
     * @mbg.generated
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shopping.receiver_district
     *
     * @mbg.generated
     */
    private String receiverDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shopping.receiver_address
     *
     * @mbg.generated
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_shopping.receiver_zip
     *
     * @mbg.generated
     */
    private String receiverZip;
}
