package com.mine.dao;

import com.mine.pojo.Cart;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;


@Mapper
public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    /**
     * 根据userId和productId查找购物车
     * @param userId
     * @param productId
     */
    Cart selectByUserIdAndProductId(@Param("userId") Integer userId,@Param("productId") Integer productId);

    //查看用户购物车信息
    List<Cart> selectCartByUserId(Integer userId);

    /**
     * 判断是否全选
     * 查询的是没有选中的数量
     * @param userId
     */
    int isCheckedAll(@Param("userId") Integer userId);

    /**
     * 删除选中的购物车中的商品
     * @param userId
     * @param stringList
     */
    int deleteProduct(@Param("userId") Integer userId ,@Param("productIdList") List<String> stringList);

    /**
     * 选中购物车中的商品。或者取消选择  全选，或全不选
     * @param userId
     * @param productId
     */
    int selectOrUnselectProduct(@Param("userId") Integer userId, @Param("productId") Integer productId, @Param("check") Integer check);

    /**
     * 查看购物车中有多少商品
     * @param userId
     * @return
     */
    int get_cart_product_count(Integer userId);

    /**
     * 查询购物车中用户已选中的商品
     * @Param userId
     * */
    List<Cart> findCartListByUserIdAndChecked(Integer userId);

    /**
     * 批量删除购物车商品
     * */
    int  batchDelete(List<Cart> cartList);

}