package com.mine.dao;

import com.mine.pojo.Product;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;


@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);


    /**
     *更新商品
     */
    int update(Product product);


    /**
     * 根据商品的id或者名字搜索
     */
    List<Product> selectByProductIdOrProductName(@Param("productId") Integer productId,@Param("productName") String productName);


    List<Product> searchProduct(@Param("integerSet") Set<Integer> integerSet, @Param("keyword") String keyword);

    /**
     * 按照商品id查询商品库存
     * */
    Integer findStockByProductId(Integer productId);

}