package com.mine.dao;

import com.mine.pojo.Shipping;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shipping record);

    int update(Shipping shipping);

    /**
     * 根据用户id和shipping 查找
     * */
    Shipping select(@Param("userId") Integer userId, @Param("shippingId") Integer shippingId);


    int delete(@Param("userId")Integer userId,@Param("shippingId") Integer shippingId);
}